coverage:
  range: 68..100
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 68%
        threshold: 5%
        base: auto 
    patch:
      default:
        # basic
        target: 68%
        threshold: 5%
        base: auto    
ignore:
  - "experiments"  # regex / glob both accepted
  - "setup.py"  # is run by pip install anyway
  - "mdp_playground/analysis/analysis_multiple.py"
  - "mdp_playground/analysis/radar_chart.py"
