name: Test PyPI Installation

on:
  push:
    branches: [ dev/jan ]
  pull_request:
    branches: [ dev/jan ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==2.2.0
        wget 'https://ray-wheels.s3-us-west-2.amazonaws.com/master/8d0c1b5e068853bf748f72b1e60ec99d240932c6/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl'
        pip install ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl[rllib,debug]
    - name: Install from PyPI
      run: |
        pip install -i https://test.pypi.org/pypi/ --extra-index-url https://pypi.org/simple mdp-playground
    - name: Basic functionality test
      run: |
        run-mdpp-experiments --help
